<?php

/**
 * Implements hook_element_info(). Defines a Form API element.
 */
function modal_hierarchical_select_element_info()
{
  $types['modal_hierarchical_select'] = array(
    '#input' => TRUE,
  );
  return $types;
}

/**
 * Implements hook_theme().
 */
function modal_hierarchical_select_theme() {
  return array(
    'modal_hierarchical_select' => array(
      'file' => 'modal_hierarchical_select.theme.inc',
      'render element' => 'element',
    ),
  );
}

/**
 * Implements hook_field_widget_info(). Defines a Field Widget.
 */
function modal_hierarchical_select_field_widget_info()
{
  $fields['modal_hierarchical_select'] = array(
    'label' => t('Modal Hierarchical Select'),
    'field types' => array('taxonomy_term_reference'),
    'behaviors' => array(
      'multiple values' => FIELD_BEHAVIOR_CUSTOM,
    ),
  );
  return $fields;
}

/**
 * Implements hook_field_widget_form(). Ties the Field Widget and the Form API element together.
 */
function modal_hierarchical_select_field_widget_form(&$form, &$form_state, $field, $instance, $langcode, $items, $delta, $element)
{
  $tids = array();
  foreach ($items as $delta => $item) {
    if (!empty($item['tid']) && $item['tid'] != 'autocreate') {
      $tids[] = $item['tid'];
    }
  }

  $element += array(
    '#type' => 'modal_hierarchical_select',
    '#default_value' => $tids,
  );

  return $element;
}