<?php

/**
 * Implements hook_element_info(). Defines a Form API element.
 */
function modal_hierarchical_select_element_info()
{
  $types['modal_hierarchical_select'] = array(
    '#input' => TRUE,
    '#theme' => array('modal_hierarchical_select'),
    '#theme_wrappers' => array('form_element'),
  );
  return $types;
}

/**
 * Implements hook_theme().
 */
function modal_hierarchical_select_theme()
{
  return array(
    'modal_hierarchical_select' => array(
      'file' => 'modal_hierarchical_select.theme.inc',
      'render element' => 'element',
    ),
  );
}

/**
 * Implements hook_field_widget_info(). Defines a Field Widget.
 */
function modal_hierarchical_select_field_widget_info()
{
  $fields['modal_hierarchical_select'] = array(
    'label' => t('Modal Hierarchical Select'),
    'field types' => array(),
    'behaviors' => array(
      'multiple values' => FIELD_BEHAVIOR_CUSTOM,
    ),
  );
  return $fields;
}

/**
 * Implements hook_field_widget_form(). Ties the Field Widget and the Form API element together.
 */
function modal_hierarchical_select_field_widget_form(&$form, &$form_state, $field, $instance, $langcode, $items, $delta, $element)
{

  drupal_add_css(drupal_get_path('module', 'modal_hierarchical_select') . '/modal_hierarchical_select.css');

  $terms = array();
  foreach ($field['settings']['allowed_values'] as $tree) {
    $terms += taxonomy_get_tree(taxonomy_vocabulary_machine_name_load($tree['vocabulary'])->vid, $tree['parent']);
  }

  print_r($items);

  foreach ($terms as $term) {
    $parent_classes = '';
    foreach ($term->parents as $parent) {
      $parent_classes .= 'parent-' . $parent . ' ';
    }

    $element['modal-hierarchical-select-item-' . $term->tid] = array(
      '#title' => $term->name,
      '#type' => 'checkbox',
      '#prefix' => '<div class="modal-hierarchical-select-item depth-' . $term->depth . ' ' . $parent_classes . '">',
      '#suffix' => '</div>',
      '#default_value' => in_array(array('tid' => $term->tid), $items),
    );
  }

  return $element;
}
